### ISSUE TITLE
Plain login prompt not hidden when SAML authentication is forced

### ISSUE THREAD

**Issue by denhyde** [pitbulk/dokuwiki-saml#13]
DokuWiki version: 2020-07-29 "Hogfather"

In lib/plugins/authsaml/conf/default.php: `'force_saml_login' => true,`

In conf/local.php: `$conf['authtype'] = 'authsaml';`

Expected behaviour: plain authentication prompt is hidden, with only a link to idP present.

Actual behaviour: both a link to idP and plain authentication prompt are displayed.

**Comment by thijskh** [comment]
Could be solved in a template, or would be great for a pull request I’d think. Maybe even in dokuwiki core instead of the plugin?

**Comment by pv2b** [comment]
#20 should resolve this one
