### ISSUE TITLE
Compatibility to DokuWiki Frusterick Manners

### ISSUE THREAD

**Issue by dreieinhalb** [pitbulk/dokuwiki-saml#4]
I'm trying to get this plugin to work with latest version of DokuWiki (Frusterick Manners), but it doesn't work as expected.

Are there plans to update this plugin to support Frusterick Manners?

**Comment by pitbulk** [comment]
Honestly right now I don't have the time to release a new version for Frusterick Manners :(

**Comment by dreieinhalb** [comment]
Too bad. I try to get it working by myself and maybe provide a patch for it. 

Unfortunately I am neither very familiar with the matter of developing DokuWiki plugins nor I'm an SAML/auth expert, but I will try my best...

**Comment by thijskh** [comment]
I have some work done to fix some open issues for an earlier version. So not complete but will be a start. I'll see if I can push that to a PR/branch, that might help you. Since, we've decomissioned that install so I won't be developing those changes further.

**Comment by thijskh** [comment]
I've looked up the code and my fixes; I submitted a number already in January and they were merged then. The remaining are now in PR #5. This was with Ponder Stibbons, so might not help a lot with Frusterick Manners. But they do improve the repo over before. Good luck!

**Comment by dreieinhalb** [comment]
@thijskh Thank you for your help and the PR, I'll have a closer look at it next week.

I also had the problem with colons in group names, but fixed it by renaming/remapping them in SimpleSAMLphp with "core:AttributeAlter". But this is maybe difficult when you deal with a lot of groups. In my case it's at the moment only one group.

**Comment by thijskh** [comment]
That point should then now be fixed. Would be good to hear if it works or what needs to be changed further.

**Comment by takuy** [comment]
@thijskh Seems like this works with the latest version of DokuWiki. Is this something you're still willing to work on? Would be good if the plugin page on DokuWiki could be updated - https://www.dokuwiki.org/plugin:authsaml

**Comment by thijskh** [comment]
I've updated the wiki
